version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "UTC"
    labels:
      - dependencies
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: "auto"
    pull-request-branch-name:
      separator: "-"
