import type { Metadata } from "next";
import { Inter, Fira_Mono, Atkinson_Hyperlegible } from "next/font/google";

import Script from "next/script";

import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import "@/css/globals.css";

const font_inter = Inter({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],

    variable: "--font-inter",
});

const font_firaMono = Fira_Mono({
    subsets: ["latin"],
    weight: ["400", "500"],
    variable: "--font-fira-mono",
});

const font_atkinson = Atkinson_Hyperlegible({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-atkinson",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            {process.env.UMAMI_WEBSITE_ID && (
                <Script
                    id="umami"
                    async
                    src={`https://https://cloud.umami.is/script.js`}
                    data-website-id={process.env.UMAMI_WEBSITE_ID}
                />
            )}
            <body
                className={`${font_inter.variable} ${font_firaMono} ${font_atkinson} antialiased lg:px-[30px]`}
            >
                <Header />
                <div className="px-[3rem] lg:px-[13rem]">
                    {children}
                    <Footer />
                </div>
            </body>
        </html>
    );
}
