// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type posts = Collections['posts']['schema']['_output']
export declare const posts: posts[]

export type projects = Collections['projects']['schema']['_output']
export declare const projects: projects[]
